version: "3"
services:

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - mern-network
    depends_on:
      - server
    stdin_open: true
    tty: true
  
  server:
    restart: always
    env_file: ./.env
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - mern-network
    depends_on:
      - db
    environment:
      - MONGODB_HOST=$MONGODB_HOST
      - MONGODB_PORT=$MONGODB_PORT
      - MONGODB_NAME=$MONGODB_NAME

  db:
    container_name: db
    image: mongo:5.0.2
    restart: always
    ports:
      - 27017:27017
    networks:
      - mern-network
    volumes:
      - mongo-data:/data/db

networks:
  mern-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
